// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI4g8p4M12nSkYVUmVOr4BCneMJzk2gFk',
    appId: '1:122948700389:web:bdf6075a8d69ace2f46c0c',
    messagingSenderId: '122948700389',
    projectId: 'medangcaffe',
    authDomain: 'medangcaffe.firebaseapp.com',
    storageBucket: 'medangcaffe.appspot.com',
    measurementId: 'G-84TXE4196F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMy3HdQHfIvA5GIFLiuhACEN1ZPZjJJcQ',
    appId: '1:122948700389:android:bd8080e59817ea50f46c0c',
    messagingSenderId: '122948700389',
    projectId: 'medangcaffe',
    storageBucket: 'medangcaffe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBLYlt5nHUlsEbGcD6hDDPUH-rc9OUTYc',
    appId: '1:122948700389:ios:6499c43f9d9cf9ebf46c0c',
    messagingSenderId: '122948700389',
    projectId: 'medangcaffe',
    storageBucket: 'medangcaffe.appspot.com',
    iosBundleId: 'com.medangcaffe.medangCaffe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBLYlt5nHUlsEbGcD6hDDPUH-rc9OUTYc',
    appId: '1:122948700389:ios:9f7b3bd3d1e0f9a0f46c0c',
    messagingSenderId: '122948700389',
    projectId: 'medangcaffe',
    storageBucket: 'medangcaffe.appspot.com',
    iosBundleId: 'com.medangcaffe.medangCaffe.RunnerTests',
  );
}
